language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm test -- --coverage
  - npm run build
after_script:
  - npm run coveralls
on:
  branch: Testing
